### ISSUE TITLE
Readme needs instructions for building a usable binary

### ISSUE THREAD

**Issue by Malcohol** [azya52/pokekon#1]
Hi there.

Really awesome work! It's great to see this interesting machine get some attention.

I tried building your project. I've built a binary using what I think are sensible commands, but when opened in Mame, the pokekon just starts the Pokekon's built-in welcome screen.

The difference seems to be that your checked-in tetris.bin binary is padded with 0xff so the code starts at 0x4000. I can easily perform that modification on the binary I have, but I assume I'm just missing a parameter for one of the asl tools.

I think it would help me and other devs a lot if you could provide the exact command-line you use to the README. 

Thanks again!

**Comment by azya52** [comment]
Hi, I added instructions to the [README](https://github.com/azya52/pokekon/tree/main/tetris).
